function sample = sampler_update( sample, params )

%% update counter
sample.i = sample.i + 1;
sample.F = get_F(sample.i,params);

%% random sweep
for tag = randperm(9)
    switch tag
        case 1
            [sample.C,sample.rec(:,tag)] = sampler_update_BCK( ...
             sample.C,sample.h,sample.b,sample.X,sample.Y,sample.Z,sample.F,sample.rec(:,tag),params);
        case 2
            [sample.C,sample.h,sample.rec(:,tag)] = sampler_update_HHH( ...
             sample.C,sample.h,sample.rec(:,tag), ...
             sample.b,sample.X,sample.Y,sample.Z,sample.F,params);
        case 3
            [sample.b,sample.K,sample.X,sample.Y,sample.Z,sample.rec(:,tag)] = sampler_update_AAA( ...
             sample.b,sample.K,sample.X,sample.Y,sample.Z,sample.rec(:,tag), ...
             sample.C,sample.h,sample.F,params);
        case 4
            [sample.b,sample.K,sample.X,sample.Y,sample.Z,sample.rec(:,tag)] = sampler_update_BBB( ...
             sample.b,sample.K,sample.X,sample.Y,sample.Z,sample.rec(:,tag), ...
             sample.C,sample.h,sample.F,params);
        case 5
            [sample.K,sample.X,sample.Y,sample.Z,sample.rec(:,tag)] = sampler_update_PP0( ...
             sample.K,sample.X,sample.Y,sample.Z,sample.rec(:,tag), ...
             sample.b,sample.C,sample.h,sample.F,params);            
        case 6
            [sample.K,sample.X,sample.Y,sample.Z,sample.rec(:,tag)] = sampler_update_PPF( ...
             sample.K,sample.X,sample.Y,sample.Z,sample.rec(:,tag), ...
             sample.C,sample.h,sample.b,sample.F,params);            
        case 7
            [sample.K,sample.X,sample.Y,sample.Z,sample.rec(:,tag)] = sampler_update_ZZZ( ...
             sample.K,sample.X,sample.Y,sample.Z,sample.rec(:,tag), ...
             sample.b,params);
        case 8
            [sample.K,sample.X,sample.Y,sample.Z,sample.rec(:,tag)] = sampler_update_ZZT( ...
             sample.K,sample.X,sample.Y,sample.Z,sample.rec(:,tag), ...
             sample.b,params);
        case 9
            [sample.K,sample.X,sample.Y,sample.Z,sample.rec(:,tag)] = sampler_update_LLL( ...
             sample.K,sample.X,sample.Y,sample.Z,sample.rec(:,tag), ...
             sample.b,params);
        otherwise
            error('Unknown sampler requested!')
    end
end

%% book-keeping
sample.L = get_log_probs(sample.F,sample.C,sample.b,sample.h,sample.K,sample.X,sample.Y,sample.Z,params);
sample.D = get_D(sample.X,sample.Y,sample.Z,sample.b,params);

