function [inactiveX, inactiveY, inactiveZ] = sampler_update_locs_cm(C, D, params)
    % updates inactive emitter locations
    s = sqrt(2 * D * diff(params.t_mid));
    inactiveX = ...
        cumsum([ ...
            params.Xm_prior_sg * randn(1, C) + params.Xm_prior_mu; ...
            s .* randn(params.N * params.K - 1, C) ...
        ]);
    inactiveY = ...
        cumsum([ ...
            params.Ym_prior_sg * randn(1, C) + params.Ym_prior_mu; ...
            s .* randn(params.N * params.K - 1, C) ...
        ]);
    inactiveZ = ...
        cumsum([ ...
            params.Zm_prior_sg * randn(1, C) + params.Zm_prior_mu .* 2 * ((rand(1, C) < 0.5) - 0.5); ...
            s .* randn(params.N * params.K - 1, C) ...
        ]);
end
